version: "3.7"

services:
  web:
    image: pablitx/dcrd-umbrel:1.7.1
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - $APP_DECRED_DCRD_P2P_PORT:$APP_DECRED_DCRD_P2P_PORT
      - $APP_DECRED_DCRD_RPC_PORT:$APP_DECRED_DCRD_RPC_PORT
    volumes:
      - ${APP_DATA_DIR}/data/:/home/decred/.dcrd/
    networks:
        default:
          ipv4_address: $APP_DECRED_DCRD_IP