version: "3.7"

services:
  dcrd:
    image: "dcrd:1.7.1"
    container_name: dcrd
    restart: unless-stopped
    build:
       context: ./decred-dcrd/build
    command: /start-dcrd.sh
#    user: "1000:1000"
    stop_grace_period: 1m
    environment:
      APP_DECRED_DCRD_IP: $APP_DECRED_DCRD_IP
      APP_DECRED_DCRD_RPC_PORT: $APP_DECRED_DCRD_RPC_PORT
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
    ports:
      - $APP_DECRED_DCRD_P2P_PORT:$APP_DECRED_DCRD_P2P_PORT
      - $APP_DECRED_DCRD_RPC_PORT:$APP_DECRED_DCRD_RPC_PORT
    volumes:
      - ${APP_DATA_DIR}/data:/storage/dcrd
      - ${APP_DATA_DIR}/logs:/storage/logs
      - ${APP_DATA_DIR}:/storage/certs
    networks:
        default:
          ipv4_address: $APP_DECRED_DCRD_IP